# Generated by Django 2.2.1 on 2019-05-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='identity',
            new_name='identit',
        ),
    ]
