# Generated by Django 2.2.1 on 2019-05-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190521_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='identit',
            new_name='identity',
        ),
    ]
